fixed error when storing xml strings
{{{
        java.net.MalformedURLException: SAXBuilder.build(String) expects the String to be a systemID, but in this instance it appears to be actual XML data.
                at org.jdom2.input.SAXBuilder.build(SAXBuilder.java:1287)
                at de.unirostock.sems.cbarchive.web.dataholder.XmlTreeMetaObjectDataholder.setXmlString(XmlTreeMetaObjectDataholder.java:70)
}}}